### ISSUE TITLE
[BUG] Doesn't compile after installing v0.0.2 from upm

### ISSUE THREAD

**Issue by laurenth-personal** [alelievr/Mixture#16]
**Describe the bug**
First I got excited, then I got this Library\PackageCache\com.alelievr.mixture@0.0.2\Editor\CustomMipMapShaderGraph\MipMapSubShader.cs(27,21): error CS1061: 'TargetSetupContext' does not contain a definition for 'AddAssetDependencyPath' and no accessible extension method 'AddAssetDependencyPath' accepting a first argument of type 'TargetSetupContext' could be found (are you missing a using directive or an assembly reference?)

:(

**To Reproduce**
1. Make a new HDRP project with 2020.2b10
2. Add upm scope and import Mixture
4. Get errors

**Setup (please complete the following information):**
 - OS: Windows
 - Unity Version: 2020.2b10

**Additional informations**
But i'm sure it's great :D .

**Comment by alelievr** [comment]
Hey Laurent :D 

I think I forgot to upgrade the shadergraph version in the dependencies to the latest available so it doesn't compile with 10.1 but it works with 10-preview.27.

I'll update the package and prepare a new release.

Thanks for reporting the issue :)

**Comment by alelievr** [comment]
Okay, the issue should be fixed with this commit: https://github.com/alelievr/Mixture/commit/0b7f05d66a159c18cbe138cde7399042bf48e8a7

I triggered a new release `0.0.3`, which should be available in open upm in few minutes :)
